includes:
  - from_url:
      url: jon4hz/meta/master/goreleaser.yml

before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh


variables:
  main: "./cmd/deadshot"
  binary_name: "deadshot"
  ldflags: -s -w -X github.com/jon4hz/deadshot/internal/version.Version={{ .Version }} -X github.com/jon4hz/deadshot/internal/version.Commit={{ .Commit }} -X github.com/jon4hz/deadshot/internal/version.Date={{ .Date }} -X github.com/jon4hz/deadshot/internal/version.BuiltBy=goreleaser
  description: "terminal based trading bot"
  github_url: "https://github.com/jon4hz/deadshot"
  maintainer: "jonah <me@jon4hz.io>"
  aur_package: |-
      # bin
      install -Dm755 "./deadshot" "${pkgdir}/usr/bin/deadshot"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/deadshot/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/deadshot.bash" "${pkgdir}/usr/share/bash-completion/completions/deadshot"
      install -Dm644 "./completions/deadshot.zsh" "${pkgdir}/usr/share/zsh/site-functions/_deadshot"
      install -Dm644 "./completions/deadshot.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/deadshot.fish"
      # man pages
      install -Dm644 "./manpages/deadshot.1.gz" "${pkgdir}/usr/share/man/man1/deadshot.1.gz"