name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: install deps
        run: sudo apt-get install -y upx make
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - 
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - 
        name: install abigen
        run: |
          GO111MODULE="off" go get -d -u github.com/ethereum/go-ethereum
          cd $(go env GOPATH)/src/github.com/ethereum/go-ethereum/cmd/abigen/
          go build -o abigen main.go
          sudo mv abigen /usr/local/bin/
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
      -
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          distribution: goreleaser-pro
          args: release --rm-dist
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
            FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
            GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
            GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
            AUR_KEY: ${{ secrets.AUR_KEY }}