name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: install deps
        run: sudo apt-get install -y upx make
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - 
        name: install abigen
        run: |
          GO111MODULE="off" go get -d -u github.com/ethereum/go-ethereum
          cd $(go env GOPATH)/src/github.com/ethereum/go-ethereum/cmd/abigen/
          go build -o abigen main.go
          sudo mv abigen /usr/local/bin/
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}